(in-package #:nilclaw/tests)
(in-suite memory-contract-suite)

(defun %mk-backends ()
  (list (make-instance 'nilclaw/memory:none-memory)
        (nilclaw/memory:make-markdown-memory :root "/tmp/nilclaw-memory-tests/")
        (nilclaw/memory:make-inmemory-lru :capacity 32)))

(test memory-contract-shared-basics
  (dolist (backend (%mk-backends))
    (is (> (length (nilclaw/memory:memory-name backend)) 0))
    (is-true (nilclaw/memory:memory-health-check backend))
    (is (= 0 (nilclaw/memory:memory-count backend)))
    (is-false (nilclaw/memory:memory-get backend "missing"))
    (is (null (nilclaw/memory:memory-recall backend "query" 10 nil)))
    (is (null (nilclaw/memory:memory-list backend nil nil)))))

(test memory-contract-shared-crud-lru
  (let ((backend (nilclaw/memory:make-inmemory-lru :capacity 32)))
    (finishes (nilclaw/memory:memory-store backend "k1" "hello world" "core"))
    (let ((entry (nilclaw/memory:memory-get backend "k1")))
      (is (string= "k1" (nilclaw/memory:memory-entry-key entry)))
      (is (search "hello" (nilclaw/memory:memory-entry-content entry)))
      (is (string= "core" (nilclaw/memory:memory-entry-category entry))))
    (is (= 1 (length (nilclaw/memory:memory-recall backend "hello" 10 nil))))
    (is (= 1 (length (nilclaw/memory:memory-list backend "core" nil))))
    (is (= 1 (nilclaw/memory:memory-count backend)))
    (nilclaw/memory:memory-store backend "k2" "second" "core")
    (is (= 2 (nilclaw/memory:memory-count backend)))
    (is-true (nilclaw/memory:memory-forget backend "k1"))
    (is (= 1 (nilclaw/memory:memory-count backend)))
    (is-false (nilclaw/memory:memory-get backend "k1"))))

(test memory-contract-none-noop
  (let ((backend (make-instance 'nilclaw/memory:none-memory)))
    (finishes (nilclaw/memory:memory-store backend "a" "b" "core" "sess"))
    (is-false (nilclaw/memory:memory-get backend "a"))
    (is (null (nilclaw/memory:memory-recall backend "b" 10 "sess")))
    (is (null (nilclaw/memory:memory-list backend "core" "sess")))
    (is (= 0 (nilclaw/memory:memory-count backend)))
    (is-false (nilclaw/memory:memory-forget backend "a"))))

(test memory-contract-markdown-append-only
  (let ((backend (nilclaw/memory:make-markdown-memory :root "/tmp/nilclaw-memory-tests/")))
    (is (string= "markdown" (nilclaw/memory:memory-name backend)))
    (is-true (nilclaw/memory:memory-health-check backend))
    (nilclaw/memory:memory-store backend "k1" "first content" "core")
    (is (= 1 (nilclaw/memory:memory-count backend)))
    (let ((entry (nilclaw/memory:memory-get backend "k1")))
      (is (search "k1" (nilclaw/memory:memory-entry-content entry)))
      (is (search "first content" (nilclaw/memory:memory-entry-content entry))))
    (is (= 1 (length (nilclaw/memory:memory-recall backend "first" 10 nil))))
    (is (= 1 (length (nilclaw/memory:memory-list backend "core" nil))))
    (nilclaw/memory:memory-store backend "k2" "second content" "core")
    (is (= 2 (nilclaw/memory:memory-count backend)))
    (is-false (nilclaw/memory:memory-forget backend "k1"))
    (is (= 2 (nilclaw/memory:memory-count backend)))))
