(in-package #:nilclaw/memory)

(defclass inmemory-lru (memory-backend)
  ((table :initform (make-hash-table :test #'equal) :accessor lru-table)
   (capacity :initarg :capacity :initform 1024 :accessor lru-capacity)
   (order :initform '() :accessor lru-order)))

(defun make-inmemory-lru (&key (capacity 1024))
  (make-instance 'inmemory-lru :capacity capacity))

(defun %lru-touch (backend key)
  (setf (lru-order backend) (cons key (remove key (lru-order backend) :test #'equal))))

(defun %lru-evict-if-needed (backend)
  (loop while (> (hash-table-count (lru-table backend)) (lru-capacity backend)) do
    (let ((last (car (last (lru-order backend)))))
      (when last
        (remhash last (lru-table backend))
        (setf (lru-order backend) (butlast (lru-order backend)))))))

(defmethod memory-name ((backend inmemory-lru)) (declare (ignore backend)) "memory")
(defmethod memory-health-check ((backend inmemory-lru)) (declare (ignore backend)) t)
(defmethod memory-count ((backend inmemory-lru)) (hash-table-count (lru-table backend)))
(defmethod memory-get ((backend inmemory-lru) key)
  (declare (type string key))
  (multiple-value-bind (entry found) (gethash key (lru-table backend))
    (when found (%lru-touch backend key))
    entry))
(defmethod memory-recall ((backend inmemory-lru) query limit &optional session-id)
  (declare (type string query) (type integer limit) (ignore session-id))
  (let ((out '()))
    (maphash (lambda (k v)
               (declare (ignore k))
               (when (search (string-downcase query) (string-downcase (memory-entry-content v)))
                 (push v out)))
             (lru-table backend))
    (subseq (nreverse out) 0 (min limit (length out)))))
(defmethod memory-list ((backend inmemory-lru) &optional category session-id)
  (declare (type (or null string) category session-id))
  (let ((out '()))
    (maphash (lambda (k v)
               (declare (ignore k))
               (when (and (or (null category) (string= category (memory-entry-category v)))
                          (or (null session-id)
                              (and (memory-entry-session-id v)
                                   (string= session-id (memory-entry-session-id v)))))
                 (push v out)))
             (lru-table backend))
    (nreverse out)))
(defmethod memory-store ((backend inmemory-lru) key content category &optional session-id)
  (let ((entry (%make-entry key content category session-id)))
    (setf (gethash key (lru-table backend)) entry)
    (%lru-touch backend key)
    (%lru-evict-if-needed backend)
    nil))
(defmethod memory-forget ((backend inmemory-lru) key)
  (let ((ok (nth-value 1 (gethash key (lru-table backend)))))
    (remhash key (lru-table backend))
    (setf (lru-order backend) (remove key (lru-order backend) :test #'equal))
    ok))
