(in-package #:nilclaw/memory)

(defclass markdown-memory (memory-backend)
  ((root :initarg :root :initform "/tmp/nilclaw-memory" :accessor md-root)
   (entries :initform (make-hash-table :test #'equal) :accessor md-entries)))

(defun make-markdown-memory (&key (root "/tmp/nilclaw-memory"))
  (ensure-directories-exist (merge-pathnames "dummy" root))
  (make-instance 'markdown-memory :root root))

(defmethod memory-name ((backend markdown-memory)) (declare (ignore backend)) "markdown")
(defmethod memory-health-check ((backend markdown-memory))
  (not (null (probe-file (md-root backend)))))
(defmethod memory-count ((backend markdown-memory)) (hash-table-count (md-entries backend)))
(defmethod memory-get ((backend markdown-memory) key)
  (gethash key (md-entries backend)))
(defmethod memory-recall ((backend markdown-memory) query limit &optional session-id)
  (declare (ignore session-id))
  (let ((out '()))
    (maphash (lambda (k v)
               (declare (ignore k))
               (when (search (string-downcase query) (string-downcase (memory-entry-content v)))
                 (push v out)))
             (md-entries backend))
    (subseq (nreverse out) 0 (min limit (length out)))))
(defmethod memory-list ((backend markdown-memory) &optional category session-id)
  (declare (ignore session-id))
  (let ((out '()))
    (maphash (lambda (k v)
               (declare (ignore k))
               (when (or (null category) (string= category (memory-entry-category v)))
                 (push v out)))
             (md-entries backend))
    (nreverse out)))
(defmethod memory-store ((backend markdown-memory) key content category &optional session-id)
  (let ((entry (%make-entry key (format nil "# ~A~%~%~A" key content) category session-id))
        (path (merge-pathnames (format nil "~A.md" key) (md-root backend))))
    (with-open-file (out path :direction :output :if-exists :supersede :if-does-not-exist :create)
      (write-string (memory-entry-content entry) out))
    (setf (gethash key (md-entries backend)) entry)
    nil))
(defmethod memory-forget ((backend markdown-memory) key)
  (declare (ignore backend key))
  nil)
