(in-package #:nilclaw/security)

(declaim (optimize (safety 3) (debug 3)))

(defparameter *max-analysis-len* 8192)

(defun %trim (s) (string-trim '(#\Space #\Tab #\Newline #\Return) s))

(defun %basename (cmd)
  (let* ((x (%trim cmd))
         (sp (position #\Space x))
         (head (if sp (subseq x 0 sp) x))
         (slash (position #\/ head :from-end t)))
    (if slash (subseq head (1+ slash)) head)))

(defun contains-single-ampersand (s)
  (let ((in-single nil) (in-double nil) (escape nil))
    (loop for i from 0 below (length s)
          for ch = (char s i)
          do
          (cond
            (escape (setf escape nil))
            ((char= ch #\\) (setf escape t))
            ((and (char= ch #\') (not in-double)) (setf in-single (not in-single)))
            ((and (char= ch #\") (not in-single)) (setf in-double (not in-double)))
            ((and (char= ch #\&) (not in-single) (not in-double))
             (let ((prev (and (> i 0) (char s (1- i))))
                   (next (and (< (1+ i) (length s)) (char s (1+ i)))))
               (unless (or (char= prev #\&) (char= next #\&) (char= prev #\\))
                 (return-from contains-single-ampersand t))))))
    nil))

(defun has-percent-var (s)
  (loop for i from 0 below (1- (length s))
        thereis (and (char= (char s i) #\%)
                     (not (char= (char s (1+ i)) #\%)))))

(defun %dangerous-path-p (cmd)
  (or (search "../" cmd)
      (search " /" cmd)
      (search " /tmp/" cmd)
      (search " /etc/" cmd)
      (search " /home/" cmd)))

(defun %bootstrap-delete-safe-p (cmd)
  (let ((c (%trim cmd)))
    (or (string= c "rm BOOTSTRAP.md")
        (string= c "trash BOOTSTRAP.md")
        (string= c "rm -f -- ./BOOTSTRAP.md"))))

(defun %unsafe-syntax-p (cmd allow-raw-url-chars)
  (or (search "`" cmd)
      (search "$(" cmd)
      (search "${" cmd)
      (search "<(" cmd)
      (search ">(" cmd)
      (search ";" cmd)
      (and (contains-single-ampersand cmd) (not allow-raw-url-chars))
      (and (or (position #\Newline cmd) (position #\Return cmd))
           (let ((parts (remove-if #'(lambda (x) (string= (%trim x) ""))
                                   (uiop:split-string cmd :separator '(#\Newline #\Return)))))
             (some #'(lambda (p) (not (string= (%basename p) "ls"))) parts)))
      (and (or (search ">>" cmd) (search ">" cmd))
           (not (search ">/dev/null" cmd))
           (not (search "2>/dev/null" cmd))
           (not (search ">\"/dev/null\"" cmd))
           (not (search "\"a > b\"" cmd)))))

(defun %token-allowed-p (base cmd allowed)
  (let ((trimmed (mapcar #'%trim allowed)))
    (or (member "*" trimmed :test #'string=)
        (member base trimmed :test #'string=)
        (some (lambda (entry)
                (and (>= (length entry) 3)
                     (string= " *" (subseq entry (- (length entry) 2)))
                     (string= base (%basename (subseq entry 0 (- (length entry) 2))))
                     (not (and (string= base "git")
                               (or (search " config " cmd) (search " config" cmd))))))
              trimmed))))

(defun %split-command-chain (cmd)
  (let ((normalized (cl-ppcre:regex-replace-all "(&&|\\|\\|)" cmd "|"))
        (pieces nil))
    (setf pieces (uiop:split-string normalized :separator '(#\| #\& #\Newline #\Return)))
    (remove-if #'(lambda (x) (string= (%trim x) "")) pieces)))

(defun is-command-allowed (policy cmd)
  (let ((c (%trim cmd)))
    (cond
      ((eq (policy-autonomy policy) :yolo) t)
      ((or (null c) (string= c "")) nil)
      ((> (length c) *max-analysis-len*) nil)
      ((eq (policy-autonomy policy) :read-only) nil)
      ((and (search "BOOTSTRAP.md" c) (not (%bootstrap-delete-safe-p c))) nil)
      ((and (%dangerous-path-p c) (search "BOOTSTRAP.md" c) (not (%bootstrap-delete-safe-p c))) nil)
      ((%unsafe-syntax-p c (policy-allow-raw-url-chars policy)) nil)
      (t
       (let ((allowed (or (policy-allowed-commands policy)
                          (resolve-allowed-commands (policy-autonomy policy) nil))))
         (every (lambda (segment)
                  (let* ((tokens (uiop:split-string (%trim segment) :separator '(#\Space)))
                         (first (or (find-if (lambda (x) (and (> (length x) 0) (not (search "=" x)))) tokens)
                                    (car tokens)))
                         (base (%basename (or first ""))))
                    (%token-allowed-p base c allowed)))
                (%split-command-chain c)))))))

(defun classify-command-risk (cmd)
  (let ((c (%trim cmd)))
    (cond
      ((> (length c) *max-analysis-len*) :high)
      ((or (search "rm -rf" c) (search "rm -fr" c) (search "sudo" c) (search "dd " c)
           (search "shutdown" c) (search "reboot" c)
           (search "curl " c) (search "wget " c))
       (if (%bootstrap-delete-safe-p c) :low :high))
      ((or (search "git reset" c) (search "git commit" c) (search "git push" c)
           (search "git rebase" c) (search "git merge" c) (search "git clean" c)
           (search "npm install" c) (search "npm publish" c)
           (search "cargo add" c) (search "cargo publish" c) (search "cargo clean" c)
           (search "touch " c) (search "mkdir " c) (search "mv " c) (search "cp " c))
       :medium)
      (t :low))))

(defun validate-command-execution (policy cmd &key approved)
  (if (eq (policy-autonomy policy) :yolo)
      (values :low nil)
      (if (not (is-command-allowed policy cmd))
          (values nil :command-not-allowed)
          (let ((risk (classify-command-risk cmd)))
            (cond
              ((and (eq risk :high)
                    (policy-block-high-risk-commands policy)
                    (not (eq (policy-autonomy policy) :full)))
               (values nil :high-risk-blocked))
              ((and (eq risk :medium)
                    (policy-require-approval-for-medium-risk policy)
                    (not approved)
                    (not (eq (policy-autonomy policy) :full)))
               (values nil :approval-required))
              (t (values risk nil)))))))
